import Image from 'next/image'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Image src="/logo.png" alt="Up Arrow" width="80" height="35" />
          <p>ACME</p>
        </header>
        {children}</body>
    </html>
  )
}
